name: Flutter Web Static Deployment

on:
  push:
    branches: ["master"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.0"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web

      - name: List build/web contents
        run: ls -la build/web

      - name: Deploy to Railway (deploy branch)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

<<<<<<< HEAD
          # Mover build a un lugar temporal fuera del repo
=======
          # Guardar build temporalmente (fuera del repo)
>>>>>>> d436c24 (Fixed some things)
          mkdir -p /tmp/flutter-web-build
          cp -r build/web/* /tmp/flutter-web-build/

          # Cambiar a rama deploy
          git fetch
          git checkout --orphan deploy
          git reset --hard
          git clean -fdx

          # Copiar desde /tmp al root del proyecto
          cp -r /tmp/flutter-web-build/* .

          # Commit y push
          git add .
          git commit -m "Deploy from GitHub Actions"
          git push --force origin deploy
